[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "latlonghelper"
dynamic = ["version"]
description = 'A package for cleaning and utilizing geospatial data. Allows the use of geospatial data to help create summarizations such as distance or create rudimentary plots via the binning functionality included in the package.'
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
keywords = []
authors = [
  { name = "Paul Raadnui" },
  { name = "Ashifa Hassam" },
  { name = "Amar Gill" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
  "License :: OSI Approved :: MIT License",
]
dependencies = [
  "pandas",
  "matplotlib",
  "seaborn"
]

[project.urls]
Documentation = "https://UBC-MDS.github.io/latlonghelper/"
Source = "https://github.com/UBC-MDS/latlonghelper"
Issues = "https://github.com/UBC-MDS/latlonghelper/issues"

[tool.hatch.version]
source = "vcs"
raw-options = { version_scheme = "no-guess-dev", local_scheme = "no-local-version" }

[tool.hatch.build.hooks.vcs]
version-file = "src/latlonghelper/__version__.py"

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/latlonghelper tests}"

[tool.coverage.run]
source_pkgs = ["latlonghelper", "tests"]
branch = true
parallel = true
omit = [
  "src/latlonghelper/__about__.py",
]

[tool.coverage.paths]
latlonghelper = ["src/latlonghelper", "*/latlonghelper/src/latlonghelper"]
tests = ["tests", "*/latlonghelper/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]

[project.optional-dependencies]
dev = [
  "pytest",
  "pytest-cov",
  "hatch-vcs",
]
docs = [
  "quartodoc",
]